name: bookworm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  simple_gradient_text: ^1.3.0
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  flutter_chart: ^0.1.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svgicons/
    - assets/images/authorspics/
    - assets/images/bookcovers/


